In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

headers = {'User-Agent' : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54"}

player_list=[]

for i in range(1,21):
    url =f"https://www.transfermarkt.com/spieler-statistik/wertvollstespieler/marktwertetop?ajax=yw1&page={i}"
    r = requests.get(url, headers=headers)

    r.status_code

    soup = BeautifulSoup(r.text, 'html.parser')

    player_info = soup.find_all('tr', class_=['odd','even'])


  

    for info in player_info:
        player=info.find_all("td")
        
        number = player[0].text
        name = player[3].text
        position = player[4].text
        age = player[5].text
        nation = player[6].img['alt']
        team = player[7].img['alt']
        value = player[8].text.strip()
        
        player_list.append([number, name, position, age, nation, team, value])
        
    time.sleep(1)
    
df=pd.DataFrame(player_list, columns=['number', 'name', 'position', 'age', 'nation', 'team', 'value'])
df

df.to_csv('transfermarkt500.csv', index=False)

,number,name,position,age,nation,team,value
0,1,Kylian Mbappé,Centre-Forward,23,France,Paris Saint-Germain,€160.00m
1,2,Erling Haaland,Centre-Forward,22,Norway,Manchester City,€150.00m
2,3,Vinicius Junior,Left Winger,22,Brazil,Real Madrid,€100.00m
3,4,Phil Foden,Central Midfield,22,England,Manchester City,€90.00m
4,5,Mohamed Salah,Right Winger,30,Egypt,Liverpool FC,€90.00m
...,...,...,...,...,...,...,...
495,496,Benjamin Bourigeaud,Right Midfield,28,France,Stade Rennais FC,€18.00m
496,497,Dean Henderson,Goalkeeper,25,England,Nottingham Forest,€18.00m
497,498,Joe Gomez,Centre-Back,25,England,Liverpool FC,€18.00m
498,499,Alex Telles,Left-Back,29,Brazil,Sevilla FC,€18.00m
499,500,Zeki Celik,Right-Back,25,Turkey,AS Roma,€18.00m