In [2]:
import pandas as pd
import numpy as np

In [24]:

file = pd.read_csv('data/FIFA23_official_data.csv', encoding_errors='ignore')
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16710 entries, 0 to 16709
Data columns (total 65 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        16710 non-null  int64
 1   Name                      16710 non-null  object
 2   Age                       16710 non-null  int64
 3   Photo                     16710 non-null  object
 4   Nationality               16710 non-null  object
 5   Flag                      16710 non-null  object
 6   Overall                   16710 non-null  int64
 7   Potential                 16710 non-null  int64
 8   Club                      16446 non-null  object
 9   Club Logo                 16710 non-null  object
 10  Value                     16710 non-null  object
 11  Wage                      16710 non-null  object
 12  Special                   16710 non-null  int64
 13  Preferred Foot            16710 non-null  object
 14  International Reputation  16710 non-null  float64
 15  Weak Foot                 16710 non-null  float64
 16  Skill Moves               16710 non-null  float64
 17  Work Rate                 16710 non-null  object
 18  Body Type                 16681 non-null  object
 19  Real Face                 16681 non-null  object
 20  Position                  16684 non-null  object
 21  Jersey Number             16684 non-null  float64
 22  Joined                    15198 non-null  object
 23  Loaned From               1132 non-null   object
 24  Contract Valid Until      16359 non-null  object
 25  Height                    16710 non-null  object
 26  Weight                    16710 non-null  object
 27  Crossing                  16710 non-null  float64
 28  Finishing                 16710 non-null  float64
 29  HeadingAccuracy           16710 non-null  float64
 30  ShortPassing              16710 non-null  float64
 31  Volleys                   16673 non-null  float64
 32  Dribbling                 16710 non-null  float64
 33  Curve                     16673 non-null  float64
 34  FKAccuracy                16710 non-null  float64
 35  LongPassing               16710 non-null  float64
 36  BallControl               16710 non-null  float64
 37  Acceleration              16710 non-null  float64
 38  SprintSpeed               16710 non-null  float64
 39  Agility                   16673 non-null  float64
 40  Reactions                 16710 non-null  float64
 41  Balance                   16673 non-null  float64
 42  ShotPower                 16710 non-null  float64
 43  Jumping                   16673 non-null  float64
 44  Stamina                   16710 non-null  float64
 45  Strength                  16710 non-null  float64
 46  LongShots                 16710 non-null  float64
 47  Aggression                16710 non-null  float64
 48  Interceptions             16702 non-null  float64
 49  Positioning               16702 non-null  float64
 50  Vision                    16673 non-null  float64
 51  Penalties                 16710 non-null  float64
 52  Composure                 16459 non-null  float64
 53  Marking                   892 non-null    float64
 54  StandingTackle            16710 non-null  float64
 55  SlidingTackle             16673 non-null  float64
 56  GKDiving                  16710 non-null  float64
 57  GKHandling                16710 non-null  float64
 58  GKKicking                 16710 non-null  float64
 59  GKPositioning             16710 non-null  float64
 60  GKReflexes                16710 non-null  float64
 61  Best Position             16710 non-null  object
 62  Best Overall Rating       16710 non-null  float64
 63  Release Clause            14961 non-null  object
 64  DefensiveAwareness        15818 non-null  float64
dtypes: float64(40), int64(5), object(20)
memory usage: 8.3+ MB

In [25]:
cols = ['Name','Position','Acceleration','SprintSpeed','Agility','Stamina','Aggression']

In [26]:
file = file[cols]
temp = file.columns[2:7]
file['Total'] = file[temp].sum(axis=1)

In [27]:
file = file.dropna(axis=0)
file.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16651 entries, 0 to 16708
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          16651 non-null  object
 1   Position      16651 non-null  object
 2   Acceleration  16651 non-null  float64
 3   SprintSpeed   16651 non-null  float64
 4   Agility       16651 non-null  float64
 5   Stamina       16651 non-null  float64
 6   Aggression    16651 non-null  float64
 7   Total         16651 non-null  float64
dtypes: float64(6), object(2)
memory usage: 1.1+ MB

In [28]:
file.to_csv("./data/processed_data.csv")

In [29]:
file.head(50)

,Name,Position,Acceleration,SprintSpeed,Agility,Stamina,Aggression,Total
0,Bruno Fernandes,"<span class=""pos pos18"">CAM",77.0,73.0,80.0,91.0,78.0,399.0
1,L. Goretzka,"<span class=""pos pos11"">LDM",78.0,83.0,76.0,88.0,81.0,406.0
2,L. Suárez,"<span class=""pos pos24"">RS",76.0,69.0,75.0,78.0,87.0,385.0
3,K. De Bruyne,"<span class=""pos pos13"">RCM",76.0,76.0,79.0,89.0,76.0,396.0
4,M. Acuña,"<span class=""pos pos7"">LB",77.0,76.0,83.0,90.0,84.0,410.0
5,J. Kimmich,"<span class=""pos pos9"">RDM",77.0,65.0,84.0,94.0,89.0,409.0
6,Paulinho,"<span class=""pos pos15"">LCM",73.0,71.0,72.0,91.0,81.0,388.0
7,G. Wijnaldum,"<span class=""pos pos28"">SUB",78.0,76.0,84.0,93.0,75.0,406.0
8,E. Can,"<span class=""pos pos28"">SUB",67.0,87.0,72.0,88.0,88.0,402.0
9,A. Griezmann,"<span class=""pos pos26"">LS",80.0,80.0,92.0,86.0,73.0,411.0
10,L. Modrić,"<span class=""pos pos13"">RCM",76.0,70.0,91.0,83.0,62.0,382.0
11,Marcos Llorente,"<span class=""pos pos12"">RM",86.0,90.0,82.0,90.0,83.0,431.0
12,Sergio Ramos,"<span class=""pos pos6"">LCB",71.0,69.0,77.0,78.0,90.0,385.0
13,D. Alaba,"<span class=""pos pos7"">LB",78.0,77.0,76.0,75.0,74.0,380.0
14,Merino,"<span class=""pos pos13"">RCM",73.0,75.0,76.0,84.0,81.0,389.0
15,N. Barella,"<span class=""pos pos13"">RCM",80.0,76.0,91.0,95.0,79.0,421.0
16,Alex Telles,"<span class=""pos pos28"">SUB",81.0,84.0,75.0,85.0,76.0,401.0
17,F. de Jong,"<span class=""pos pos13"">RCM",80.0,82.0,88.0,90.0,75.0,415.0
18,M. Sabitzer,"<span class=""pos pos28"">SUB",75.0,81.0,75.0,85.0,77.0,393.0
19,J. Cuadrado,"<span class=""pos pos12"">RM",91.0,89.0,94.0,78.0,78.0,430.0
20,Koke,"<span class=""pos pos13"">RCM",72.0,69.0,73.0,93.0,79.0,386.0
21,João Cancelo,"<span class=""pos pos7"">LB",86.0,84.0,80.0,90.0,73.0,413.0
22,L. Digne,"<span class=""pos pos7"">LB",81.0,77.0,74.0,86.0,76.0,394.0
23,F. Kostić,"<span class=""pos pos16"">LM",89.0,88.0,76.0,90.0,80.0,423.0
24,T. Alexander-Arnold,"<span class=""pos pos3"">RB",77.0,80.0,73.0,88.0,74.0,392.0
25,S. Milinković-Savić,"<span class=""pos pos13"">RCM",66.0,70.0,62.0,91.0,79.0,368.0
26,A. Vidal,"<span class=""pos pos28"">SUB",66.0,65.0,81.0,78.0,92.0,382.0
27,P. Pogba,"<span class=""pos pos9"">RDM",63.0,77.0,73.0,77.0,78.0,368.0
28,Casemiro,"<span class=""pos pos10"">CDM",60.0,69.0,61.0,89.0,91.0,370.0
29,L. Messi,"<span class=""pos pos23"">RW",91.0,80.0,91.0,72.0,44.0,378.0
30,Renato Sanches,"<span class=""pos pos15"">LCM",86.0,83.0,85.0,87.0,84.0,425.0
31,L. Ocampos,"<span class=""pos pos27"">LW",80.0,82.0,79.0,91.0,82.0,414.0
32,Jordi Alba,"<span class=""pos pos7"">LB",87.0,86.0,90.0,87.0,75.0,425.0
33,R. Lewandowski,"<span class=""pos pos25"">ST",77.0,79.0,77.0,76.0,81.0,390.0
34,M. Salah,"<span class=""pos pos23"">RW",89.0,91.0,91.0,85.0,63.0,419.0
35,Angeliño,"<span class=""pos pos7"">LB",85.0,73.0,83.0,85.0,77.0,403.0
36,Cristiano Ronaldo,"<span class=""pos pos25"">ST",85.0,88.0,86.0,77.0,63.0,399.0
37,12 Roberto Carlos,"<span class=""pos pos28"">SUB",77.0,78.0,74.0,60.0,74.0,363.0
38,Canales,"<span class=""pos pos16"">LM",85.0,82.0,83.0,80.0,68.0,398.0
39,H. Kane,"<span class=""pos pos25"">ST",65.0,74.0,71.0,83.0,80.0,373.0
40,19 Dani Alves,"<span class=""pos pos3"">RB",75.0,77.0,84.0,74.0,82.0,392.0
41,M. Brozović,"<span class=""pos pos10"">CDM",70.0,68.0,79.0,94.0,85.0,396.0
42,M. Verratti,"<span class=""pos pos14"">CM",68.0,60.0,91.0,76.0,89.0,384.0
43,Saúl,"<span class=""pos pos28"">SUB",69.0,72.0,73.0,86.0,76.0,376.0
44,Thiago,"<span class=""pos pos15"">LCM",72.0,55.0,91.0,74.0,72.0,364.0
45,J. Veretout,"<span class=""pos pos11"">LDM",84.0,72.0,76.0,85.0,84.0,401.0
46,J. Henderson,"<span class=""pos pos13"">RCM",67.0,66.0,69.0,86.0,83.0,371.0
47,I. Gündoğan,"<span class=""pos pos15"">LCM",66.0,65.0,77.0,74.0,70.0,352.0
48,R. Nainggolan,"<span class=""pos pos15"">LCM",70.0,71.0,69.0,69.0,85.0,364.0
49,T. Delaney,"<span class=""pos pos28"">SUB",77.0,74.0,73.0,87.0,85.0,396.0

In [19]:
file.loc[file['Name'] == "E. Mbappé"]

Empty DataFrame
Columns: [Name, Position, Acceleration, SprintSpeed, Agility, Stamina, Aggression, Total]
Index: []

In [30]:
file['Position'] = file['Position'].str.split('>').str[-1].str.strip()
file

,Name,Position,Acceleration,SprintSpeed,Agility,Stamina,Aggression,Total
0,Bruno Fernandes,CAM,77.0,73.0,80.0,91.0,78.0,399.0
1,L. Goretzka,LDM,78.0,83.0,76.0,88.0,81.0,406.0
2,L. Suárez,RS,76.0,69.0,75.0,78.0,87.0,385.0
3,K. De Bruyne,RCM,76.0,76.0,79.0,89.0,76.0,396.0
4,M. Acuña,LB,77.0,76.0,83.0,90.0,84.0,410.0
...,...,...,...,...,...,...,...,...
16704,B. Voll,RES,24.0,25.0,27.0,21.0,21.0,118.0
16705,18 L. Clayton,RES,15.0,21.0,34.0,26.0,16.0,112.0
16706,�. Dobre,RES,16.0,22.0,30.0,24.0,18.0,110.0
16707,21 Xue Qinghao,RES,22.0,17.0,36.0,20.0,13.0,108.0
16708,A. Shaikh,SUB,20.0,18.0,26.0,19.0,24.0,107.0

In [31]:
file.to_csv("./data/processed_data.csv")

In [39]:
file.loc[file['Name'] == "H. Son"]

,Name,Position,Acceleration,SprintSpeed,Agility,Stamina,Aggression,Total
129,H. Son,LW,85.0,90.0,86.0,88.0,62.0,411.0