In [4]:
import pandas as pd
import numpy as np

# df = pd.read_csv("./data/EPL_13_14/offensive.csv")
# df = pd.read_csv("./data/La_13-14/offensive.csv")
# df = pd.read_csv("./data/Bun_13-14/offensive.csv")
# df = pd.read_csv("./data/Li1_13-14/offensive.csv")
# df = pd.read_csv("./data/Se_13-14/offensive.csv")
#df.info()

In [5]:
df1 = df[["name","age","position1","position2", "Apps","Mins", "Goals", "Assists", "SpG","KeyP", "Drb", "Rating" ]]
df1['WC_Rating'] = 0
df1

NameError: name 'df' is not defined

In [ ]:
# ## 25세 이하 선수들 df2

# idx_age = df1[df1['age'] > 26].index
# df2 = df1.drop(idx_age)

In [ ]:
## 출전 경기, 선발과 교체로 분할

df_app = df1[['Apps']]
df_app['start'] = df_app.Apps.str.split('(').str[0]
df_app['sub'] = df_app.Apps.str.split('(').str[1];
df_app['sub'] = df_app['sub'].replace('[\),]','', regex=True)
df_app = df_app.fillna(0)
df_app

C:\Users\user\AppData\Local\Temp\ipykernel_25812\731944388.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_app['start'] = df_app.Apps.str.split('(').str[0]
C:\Users\user\AppData\Local\Temp\ipykernel_25812\731944388.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_app['sub'] = df_app.Apps.str.split('(').str[1];
C:\Users\user\AppData\Local\Temp\ipykernel_25812\731944388.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_app['sub'] = df_app['sub'].replace('[\),]','', regex=True)

       Apps start sub
0     29(2)    29   2
1        30    30   0
2         3     3   0
3     24(3)    24   3
4     29(4)    29   4
..      ...   ...  ..
295  21(10)    21  10
296   24(7)    24   7
297       1     1   0
298   12(5)    12   5
299    6(1)     6   1

[300 rows x 3 columns]

In [ ]:
df1 = df1.replace('-',0)
## 데이터 타입 형변환 (object > 정수형)
df_app['start'] = df_app['start'].astype(int)
df_app['sub'] = df_app['sub'].astype(int)
df_app.dtypes


df1['Mins'] = df1['Mins'].astype(float)
df1['Goals'] = df1['Goals'].astype(float)
df1['Assists'] = df1['Assists'].astype(float)
df1['SpG'] = df1['SpG'].astype(float)
df1['KeyP'] = df1['KeyP'].astype(float)
df1['Drb'] = df1['Drb'].astype(float)
df1['Rating'] = df1['Rating'].astype(float)
df1.dtypes

name          object
age            int64
position1     object
position2     object
Apps          object
Mins         float64
Goals        float64
Assists      float64
SpG          float64
KeyP         float64
Drb          float64
Rating       float64
WC_Rating      int64
dtype: object

In [ ]:
# ## 25세 이하 / 출전경기 19경기 이상인 선수
# df_app2 = pd.DataFrame(df_app.sum(axis=1))
# df_app2.columns = ["Apps"]

# idx_app = df_app2[df_app2['Apps'] < 19].index
# df_app3 = df_app2.drop(idx_app)
# df_app3

In [ ]:
df4 = df1.fillna('')
#포지션별 분류
df5 = ((df4['position1'].str.contains('AM'))|df4['position1'].str.contains('FW')
      |df4['position2'].str.contains('AM')|df4['position2'].str.contains('FW'))
df6 = pd.DataFrame(df5)
df6.columns = ["Position"]
df6['Position'] = df6['Position'].astype(int)
df6

     Position
0           1
1           1
2           0
3           1
4           0
..        ...
295         1
296         0
297         0
298         0
299         0

[300 rows x 1 columns]

In [ ]:
#포지션이 공격수/ 공격형 미드필더

idx_position = df6[df6['Position'] == 0].index
df_position = df6.drop(idx_position)
df_position
df7 = df1.loc[df_position.index]
df7 = df7.fillna('')
df7

,name,age,position1,position2,Apps,Mins,Goals,Assists,SpG,KeyP,Drb,Rating,WC_Rating
0,Lionel Messi Barcelona,35,AM(CR),FW,29(2),2508.0,27.0,11.0,5.0,2.4,4.6,8.34,0
1,Cristiano Ronaldo Real Madrid,37,M(L),FW,30,2545.0,31.0,9.0,7.2,1.6,2.2,8.27,0
3,Gareth Bale Real Madrid,33,M(CLR),FW,24(3),2073.0,15.0,12.0,3.3,1.5,2.1,7.75,0
6,Alexis Sánchez Barcelona,33,M(CLR),FW,27(7),2386.0,19.0,10.0,1.9,1.4,1.1,7.54,0
7,Neymar Barcelona,30,AM(CLR),FW,19(7),1742.0,9.0,8.0,2.6,1.6,3.0,7.51,0
13,Ángel Di María Real Madrid,34,M(CLR),FW,27(7),2384.0,4.0,17.0,1.8,2.6,1.4,7.46,0
15,Karim Benzema Real Madrid,34,FW,,34(1),2779.0,17.0,9.0,2.9,1.8,0.5,7.44,0
19,Carlos Vela Real Sociedad,33,M(CLR),FW,35(2),3116.0,15.0,12.0,2.2,2.1,2.0,7.42,0
21,Isco Real Madrid,30,M(CLR),FW,23(9),2001.0,8.0,6.0,1.4,2.2,2.1,7.41,0
23,Diego Costa Atletico,34,FW,,34(1),2965.0,27.0,3.0,3.1,1.3,1.7,7.40,0
30,Cesc Fàbregas Barcelona,35,M(CL),FW,28(7),2446.0,8.0,12.0,1.4,1.6,0.7,7.32,0
31,Aritz Aduriz Athletic Bilbao,41,FW,,26(5),2410.0,15.0,7.0,2.6,1.0,0.7,7.32,0
42,Iker Muniain Athletic Bilbao,29,AM(CLR),,32(3),2730.0,7.0,3.0,1.5,0.9,2.7,7.23,0
43,Antoine Griezmann Real Sociedad,31,AM(CLR),FW,31(4),2666.0,16.0,3.0,3.2,1.0,0.6,7.22,0
47,Jonathan Viera Valencia,33,AM(CLR),FW,1,79.0,0.0,0.0,1.0,0.0,5.0,7.21,0
65,Nolito Celta Vigo,36,AM(CL),,24(11),2264.0,12.0,2.0,2.3,1.4,1.3,7.13,0
67,Pedro Barcelona,35,M(CLR),FW,28(9),2367.0,15.0,8.0,1.9,1.0,0.7,7.13,0
74,Fabián Orellana Celta Vigo,36,AM(CLR),,22(8),1956.0,5.0,6.0,1.3,1.5,1.4,7.10,0
90,Oriol Riera Osasuna,36,FW,,35(2),3022.0,13.0,0.0,2.1,0.9,0.4,7.05,0
98,Giovani dos Santos Villarreal,33,AM(CLR),FW,26(4),2205.0,10.0,8.0,1.9,1.4,0.9,7.03,0
102,Charles Celta Vigo,38,FW,,29(1),2349.0,12.0,3.0,2.2,1.1,0.3,7.02,0
106,Carlos Bacca Sevilla,36,FW,,27(7),2290.0,14.0,5.0,1.9,1.0,0.9,7.01,0
111,Nordin Amrabat Malaga,35,M(CLR),FW,15,1314.0,2.0,4.0,2.1,1.7,2.3,7.00,0
112,Sergio García Espanyol,39,M(CLR),FW,37,3259.0,11.0,8.0,2.0,1.9,1.8,7.00,0
115,Miku Getafe,37,FW,,3(2),292.0,2.0,1.0,1.2,0.8,0.8,6.99,0
120,Ikechukwu Uche Villarreal,38,FW,,19(7),1657.0,13.0,2.0,1.6,0.9,0.4,6.98,0
124,Vitolo Sevilla,33,M(CLR),FW,25(4),2198.0,4.0,6.0,1.1,1.3,1.1,6.97,0
125,Raúl García Atletico,36,M(CLR),FW,18(16),1710.0,9.0,3.0,1.8,0.5,0.2,6.97,0
131,Javi Guerra Real Valladolid,40,FW,,37,3161.0,15.0,1.0,2.3,0.6,0.4,6.96,0
132,Arda Turan Atletico,35,AM(CLR),,22(8),1932.0,3.0,4.0,1.1,1.1,1.3,6.96,0
137,Ibai Gómez Athletic Bilbao,32,AM(LR),,6(12),685.0,8.0,2.0,2.6,1.3,0.7,6.94,0
141,Cristhian Stuani Espanyol,36,AM(CLR),FW,28(6),2574.0,6.0,2.0,1.5,0.6,0.6,6.94,0
149,Javier Aquino Villarreal,32,AM(R),,18(9),1695.0,1.0,4.0,0.7,1.0,1.1,6.93,0
155,Roque Santa Cruz Malaga,41,FW,,24(7),2140.0,6.0,2.0,1.6,1.0,0.6,6.92,0
161,Emiliano Armenteros Osasuna,36,AM(CLR),,27(2),2248.0,4.0,3.0,1.5,1.7,0.8,6.91,0
176,Youssef El Arabi Granada,35,AM(C),FW,34(2),2801.0,12.0,2.0,2.6,0.8,0.9,6.88,0
182,Jonas Valencia,38,AM(CLR),FW,23(8),2097.0,10.0,1.0,2.8,0.7,0.6,6.86,0
188,David Villa Atletico,40,AM(L),FW,32(4),2431.0,13.0,4.0,2.1,0.8,0.3,6.85,0
190,Fede Cartabia Valencia,29,AM(CLR),,16(9),1423.0,0.0,1.0,1.8,1.1,1.6,6.85,0
191,Joaquín Larrivey Rayo Vallecano,38,FW,,24(11),2415.0,12.0,4.0,1.9,0.7,0.1,6.85,0
202,Manu Molina Espanyol,30,AM(R),,0(1),31.0,0.0,1.0,0.0,2.0,0.0,6.83,0
206,David Barral Levante,39,FW,,25(7),2255.0,7.0,0.0,2.0,0.7,0.6,6.82,0
207,Roberto Torres Osasuna,33,AM(CLR),,25(8),2282.0,5.0,3.0,1.6,1.8,0.5,6.82,0
213,Suso Almeria,28,AM(CLR),FW,26(7),2265.0,3.0,7.0,1.9,1.0,1.7,6.81,0
234,Diego Perotti Sevilla,34,M(CLR),FW,3(7),403.0,1.0,1.0,1.1,1.0,1.6,6.77,0
235,Manu Trigueros Villarreal,31,M(CLR),FW,23(10),2017.0,1.0,1.0,1.0,0.9,0.5,6.76,0
242,Rubén Castro Real Betis,41,AM(LR),FW,22(3),2019.0,10.0,1.0,3.0,1.0,0.6,6.76,0
248,Ángel Lafita Getafe,38,M(CLR),FW,22(7),1870.0,7.0,1.0,1.4,0.7,1.0,6.75,0
249,Iago Falque Rayo Vallecano,32,AM(CLR),FW,26(2),2001.0,3.0,2.0,1.4,1.3,0.7,6.75,0
258,Kevin Gameiro Sevilla,35,FW,,20(15),1890.0,14.0,3.0,1.5,0.8,0.5,6.73,0
263,Kike Sola Athletic Bilbao,36,FW,,2(3),226.0,1.0,0.0,1.4,0.0,0.6,6.72,0
274,Jorge Molina Real Betis,40,FW,,25(7),2352.0,9.0,1.0,1.8,1.1,0.4,6.69,0
275,Jonathan Viera Rayo Vallecano,33,AM(CLR),FW,18(8),1725.0,5.0,7.0,1.9,1.4,1.2,6.69,0
276,Gonzalo Castro Real Sociedad,38,AM(LR),FW,12(11),1022.0,2.0,3.0,1.0,1.1,1.2,6.69,0
281,Dorlan Pabón Valencia,34,AM(CLR),FW,11(2),913.0,3.0,0.0,2.8,0.8,0.8,6.69,0
282,Carles Gil Elche,29,AM(CR),,29(3),2524.0,1.0,3.0,1.0,1.3,1.6,6.69,0
284,Víctor Casadesús Levante,37,AM(C),FW,13(1),1051.0,1.0,2.0,1.1,0.8,1.0,6.69,0
293,Paco Alcácer Valencia,29,AM(R),FW,17(6),1542.0,6.0,2.0,1.9,0.7,0.1,6.67,0
295,Imanol Agirretxe Real Sociedad,35,FW,,21(10),1960.0,8.0,1.0,2.0,0.4,0.4,6.67,0

In [ ]:
Laliga_list = [
    'Real Madrid',
    'Barcelona',
    'Real Betis',
    'Deportivo Alaves',
    'Athletic Bilbao',
    'Celta Vigo',
    'Villarreal',
    'Real Sociedad',
    'Atletico',
    'Espanyol',
    'Rayo Vallecano',
    'Getafe',
    'Valencia',
    'Sevilla',
    'Levante',
    'Osasuna',
    'Mallorca',
    'Elche',
    'Granada',
    'Cadiz',
    'Eibar',
    'Leganes',
    'Girona',
    'SD Huesca',
    'Real Valladolid',
    'Malaga',
    'Las Palmas',
    'Deportivo',
    'Almeria',
    'Elche',
    'Real Zaragoza',
    'Sporting Gijon',
    'Racing Santnader',
    'Tenerife',
    'Xerez'
    

]
Country = [
    'Argentina',
    'Algeria',
    'Brazil',
    'Belgium',
    'Bosnia and Herzegovina',
    'Croatia',
    'Costa Rica',
    'Colombia',
    'Cameroon',
    'Chile',
    'Denmark',
    'Egypt',
    'England',
    'Ecuador',
    'France',
    'Germany',
    'Ghana',
    'Greece',
    'Honduras',
    'Iran',
    'Iceland',
    'Ivory Coast',
    'Italy',
    'Japan',
    'Morocco',
    'Mexico',
    'Nigieria',
    'Netherlands',
    'New Zealand',
    'North Korea',
    'Saudi Arabia',
    'Spain',
    'Switzerland',
    'Serbia',
    'Sweden',
    'South Korea',
    'Senegal',
    'South Africa',
    'Slovenia',
    'Serbia',
    'Slovakia',
    'Uruguay',
    'Russia',
    'Portugal',
    'Peru',
    'Tunisia',
    'Panama',
    'Poland',
    'USA',
    'Russia',
    'Paraguay'
    
]

EPL_list = [
    'Man Utd',
    'Man City',
    'Liverpool',
    'Tottenham',
    'Brentford',
    'Chelsea',
    'Aston Villa',
    'West Ham',
    'Newcastle',
    'Crystal Palace',
    'Leicester',
    'Southampton',
    'Brighton',
    'Burnley',
    'Wolves',
    'Leeds',
    'Everton',
    'Arsenal',
    'Watford',
    'Norwich',
    'Burnley',
    'Stoke',
    'Southampton',
    'Bournemouth',
    'West Brom',
    'Huddersfield',
    'Swansea',
    'Cardiff',
    'Sunderland',
    'Hull',
    'Fulham',
    'Norwich',
    'Birmingham',
    'Bolton',
    'Wigan',
    'Blackburn',
    'Portsmouth'
    
]
Seria_list = [
    'Sassuolo',
    'AC Milan',
    'Lazio',
    'Roma',
    'Fiorentina',
    'Atalanta',
    'Inter',
    'Napoli',
    'Juventus',
    'Torino',
    'Verona',
    'Udinese',
    'Salernitana',
    'Sampdoria',
    'Empoli',
    'Bologna',
    'Venezia',
    'Genoa',
    'Cagliari',
    'Salernitana',
    'SPAL 2013',
    'Chievo',
    'Crotone',
    'Benevento',
    'Parma Calcio 1913',
    'Livorno',
    'Catania',
    'Siena',
    'Bari',
    
    
]
Ligue1_list = [
    'PSG',
    'Rennes',
    'Lille',
    'Lorient', 
    'Lyon',
    'Lens',
    'Monaco',
    'Troyes',
    'Bordeaux',
    'Angers',
    'Marseille',
    'Nantes',
    'Montpellier',
    'Nice',
    'Brest',
    'Reims',
    'Clermont Foot',
    'Starsbourg',
    'Saint-Etienne',
    'Metz',
    'Toulouse',
    'SC Bastia',
    'Guingamp',
    'Evian',
    'Valenciennes',
    'AC Ajaccio'

]
Bundesliga_list = [
    'Bayern',
    'Borussia Dortmund',
    'Borussia M.Gladbach',
    'RBL',
    'Ausburg',
    'Freiburg',
    'Eintracht Frankfurt',
    'Wolfsburg',
    'Hertha Berlin',
    'FC Koln',
    'Shuttgart',
    'Bochum',
    'Mainz',
    'Union Berlin',
    'Hoffenheim',
    'Leverkusen',
    'Greuther Fuerto',
    'Arminia Bielefeld',
    'Hamburg',
    'Hannover',
    'Werder Bremen',
    'Schalke',
    'Augsburg',
    'Stuttgart',
    'Nuernberg',
    'Braunschweig',
    'Eintracht'
    

]

In [ ]:
for i in range(len(Laliga_list)):
    df7["name"] = df7["name"].str.replace(Laliga_list[i], "")

In [ ]:
df7

,name,age,position1,position2,Apps,Mins,Goals,Assists,SpG,KeyP,Drb,Rating,WC_Rating
0,Lionel Messi,35,AM(CR),FW,29(2),2508.0,27.0,11.0,5.0,2.4,4.6,8.34,0
1,Cristiano Ronaldo,37,M(L),FW,30,2545.0,31.0,9.0,7.2,1.6,2.2,8.27,0
3,Gareth Bale,33,M(CLR),FW,24(3),2073.0,15.0,12.0,3.3,1.5,2.1,7.75,0
6,Alexis Sánchez,33,M(CLR),FW,27(7),2386.0,19.0,10.0,1.9,1.4,1.1,7.54,0
7,Neymar,30,AM(CLR),FW,19(7),1742.0,9.0,8.0,2.6,1.6,3.0,7.51,0
13,Ángel Di María,34,M(CLR),FW,27(7),2384.0,4.0,17.0,1.8,2.6,1.4,7.46,0
15,Karim Benzema,34,FW,,34(1),2779.0,17.0,9.0,2.9,1.8,0.5,7.44,0
19,Carlos Vela,33,M(CLR),FW,35(2),3116.0,15.0,12.0,2.2,2.1,2.0,7.42,0
21,Isco,30,M(CLR),FW,23(9),2001.0,8.0,6.0,1.4,2.2,2.1,7.41,0
23,Diego Costa,34,FW,,34(1),2965.0,27.0,3.0,3.1,1.3,1.7,7.40,0
30,Cesc Fàbregas,35,M(CL),FW,28(7),2446.0,8.0,12.0,1.4,1.6,0.7,7.32,0
31,Aritz Aduriz,41,FW,,26(5),2410.0,15.0,7.0,2.6,1.0,0.7,7.32,0
42,Iker Muniain,29,AM(CLR),,32(3),2730.0,7.0,3.0,1.5,0.9,2.7,7.23,0
43,Antoine Griezmann,31,AM(CLR),FW,31(4),2666.0,16.0,3.0,3.2,1.0,0.6,7.22,0
47,Jonathan Viera,33,AM(CLR),FW,1,79.0,0.0,0.0,1.0,0.0,5.0,7.21,0
65,Nolito,36,AM(CL),,24(11),2264.0,12.0,2.0,2.3,1.4,1.3,7.13,0
67,Pedro,35,M(CLR),FW,28(9),2367.0,15.0,8.0,1.9,1.0,0.7,7.13,0
74,Fabián Orellana,36,AM(CLR),,22(8),1956.0,5.0,6.0,1.3,1.5,1.4,7.10,0
90,Oriol Riera,36,FW,,35(2),3022.0,13.0,0.0,2.1,0.9,0.4,7.05,0
98,Giovani dos Santos,33,AM(CLR),FW,26(4),2205.0,10.0,8.0,1.9,1.4,0.9,7.03,0
102,Charles,38,FW,,29(1),2349.0,12.0,3.0,2.2,1.1,0.3,7.02,0
106,Carlos Bacca,36,FW,,27(7),2290.0,14.0,5.0,1.9,1.0,0.9,7.01,0
111,Nordin Amrabat,35,M(CLR),FW,15,1314.0,2.0,4.0,2.1,1.7,2.3,7.00,0
112,Sergio García,39,M(CLR),FW,37,3259.0,11.0,8.0,2.0,1.9,1.8,7.00,0
115,Miku,37,FW,,3(2),292.0,2.0,1.0,1.2,0.8,0.8,6.99,0
120,Ikechukwu Uche,38,FW,,19(7),1657.0,13.0,2.0,1.6,0.9,0.4,6.98,0
124,Vitolo,33,M(CLR),FW,25(4),2198.0,4.0,6.0,1.1,1.3,1.1,6.97,0
125,Raúl García,36,M(CLR),FW,18(16),1710.0,9.0,3.0,1.8,0.5,0.2,6.97,0
131,Javi Guerra,40,FW,,37,3161.0,15.0,1.0,2.3,0.6,0.4,6.96,0
132,Arda Turan,35,AM(CLR),,22(8),1932.0,3.0,4.0,1.1,1.1,1.3,6.96,0
137,Ibai Gómez,32,AM(LR),,6(12),685.0,8.0,2.0,2.6,1.3,0.7,6.94,0
141,Cristhian Stuani,36,AM(CLR),FW,28(6),2574.0,6.0,2.0,1.5,0.6,0.6,6.94,0
149,Javier Aquino,32,AM(R),,18(9),1695.0,1.0,4.0,0.7,1.0,1.1,6.93,0
155,Roque Santa Cruz,41,FW,,24(7),2140.0,6.0,2.0,1.6,1.0,0.6,6.92,0
161,Emiliano Armenteros,36,AM(CLR),,27(2),2248.0,4.0,3.0,1.5,1.7,0.8,6.91,0
176,Youssef El Arabi,35,AM(C),FW,34(2),2801.0,12.0,2.0,2.6,0.8,0.9,6.88,0
182,Jonas,38,AM(CLR),FW,23(8),2097.0,10.0,1.0,2.8,0.7,0.6,6.86,0
188,David Villa,40,AM(L),FW,32(4),2431.0,13.0,4.0,2.1,0.8,0.3,6.85,0
190,Fede Cartabia,29,AM(CLR),,16(9),1423.0,0.0,1.0,1.8,1.1,1.6,6.85,0
191,Joaquín Larrivey,38,FW,,24(11),2415.0,12.0,4.0,1.9,0.7,0.1,6.85,0
202,Manu Molina,30,AM(R),,0(1),31.0,0.0,1.0,0.0,2.0,0.0,6.83,0
206,David Barral,39,FW,,25(7),2255.0,7.0,0.0,2.0,0.7,0.6,6.82,0
207,Roberto Torres,33,AM(CLR),,25(8),2282.0,5.0,3.0,1.6,1.8,0.5,6.82,0
213,Suso,28,AM(CLR),FW,26(7),2265.0,3.0,7.0,1.9,1.0,1.7,6.81,0
234,Diego Perotti,34,M(CLR),FW,3(7),403.0,1.0,1.0,1.1,1.0,1.6,6.77,0
235,Manu Trigueros,31,M(CLR),FW,23(10),2017.0,1.0,1.0,1.0,0.9,0.5,6.76,0
242,Rubén Castro,41,AM(LR),FW,22(3),2019.0,10.0,1.0,3.0,1.0,0.6,6.76,0
248,Ángel Lafita,38,M(CLR),FW,22(7),1870.0,7.0,1.0,1.4,0.7,1.0,6.75,0
249,Iago Falque,32,AM(CLR),FW,26(2),2001.0,3.0,2.0,1.4,1.3,0.7,6.75,0
258,Kevin Gameiro,35,FW,,20(15),1890.0,14.0,3.0,1.5,0.8,0.5,6.73,0
263,Kike Sola,36,FW,,2(3),226.0,1.0,0.0,1.4,0.0,0.6,6.72,0
274,Jorge Molina,40,FW,,25(7),2352.0,9.0,1.0,1.8,1.1,0.4,6.69,0
275,Jonathan Viera,33,AM(CLR),FW,18(8),1725.0,5.0,7.0,1.9,1.4,1.2,6.69,0
276,Gonzalo Castro,38,AM(LR),FW,12(11),1022.0,2.0,3.0,1.0,1.1,1.2,6.69,0
281,Dorlan Pabón,34,AM(CLR),FW,11(2),913.0,3.0,0.0,2.8,0.8,0.8,6.69,0
282,Carles Gil,29,AM(CR),,29(3),2524.0,1.0,3.0,1.0,1.3,1.6,6.69,0
284,Víctor Casadesús,37,AM(C),FW,13(1),1051.0,1.0,2.0,1.1,0.8,1.0,6.69,0
293,Paco Alcácer,29,AM(R),FW,17(6),1542.0,6.0,2.0,1.9,0.7,0.1,6.67,0
295,Imanol Agirretxe,35,FW,,21(10),1960.0,8.0,1.0,2.0,0.4,0.4,6.67,0

In [6]:
df7.to_csv("Laliga_13_14_of.csv")

NameError: name 'df7' is not defined

In [7]:
df8 = pd.read_csv("13_14_of.csv")
df8

,Unnamed: 0,name,age,position1,position2,Apps,Mins,Goals,Assists,SpG,KeyP,Drb,Rating,WC_Rating
0,0,Franck Ribéry,39,AM(CL),FW,18(4),1643,10,10,2.7,2.5,5.5,8.28,0
1,2,Robert Lewandowski,34,FW,NaN,31(2),2807,20,6,3.5,1.9,3.1,8.00,0
2,3,Roberto Firmino,31,M(CLR),FW,33,2916,16,11,2.8,2.1,4.5,7.94,0
3,4,Marco Reus,33,M(CLR),FW,26(4),2221,16,13,3.7,3.0,2.7,7.91,0
4,5,Raffael,37,AM(CL),FW,34,2999,15,7,2.2,1.9,4.9,7.91,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,304,Mario Gomez,37,FW,NaN,5(4),498,3,1,1.4,0.3,0.2,6.72,0
306,306,Goran Pandev,39,M(CR),FW,17(12),1387,7,4,0.9,1.0,0.7,6.71,0
307,310,Victor Obinna,35,FW,NaN,4(6),398,2,0,1.8,0.7,0.9,6.71,0
308,316,Josip Ilicic,34,AM(CLR),FW,13(8),1108,3,1,1.9,1.0,0.9,6.71,0
309,318,Valter Birsa,36,M(CLR),FW,10(5),756,2,0,1.5,1.2,1.0,6.70,0

In [8]:
df9 = pd.read_csv("./data/wc_2014/offensive.csv")
for i in range(len(Country)):
    df9["name"] = df9["name"].str.replace(Country[i], "")

NameError: name 'Country' is not defined

In [ ]:
for i in range(len(df8)):
    for k in range(len(df9)):
        if df8["name"][i] == df9["name"][k]:
            df8["WC_Rating"][i] = df9["Rating"][k]

C:\Users\CHANHO KIM\AppData\Local\Temp\ipykernel_28556\520923048.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df8["WC_Rating"][i] = df9["Rating"][k]

In [9]:
df8

,Unnamed: 0,name,age,position1,position2,Apps,Mins,Goals,Assists,SpG,KeyP,Drb,Rating,WC_Rating
0,0,Franck Ribéry,39,AM(CL),FW,18(4),1643,10,10,2.7,2.5,5.5,8.28,0
1,2,Robert Lewandowski,34,FW,NaN,31(2),2807,20,6,3.5,1.9,3.1,8.00,0
2,3,Roberto Firmino,31,M(CLR),FW,33,2916,16,11,2.8,2.1,4.5,7.94,0
3,4,Marco Reus,33,M(CLR),FW,26(4),2221,16,13,3.7,3.0,2.7,7.91,0
4,5,Raffael,37,AM(CL),FW,34,2999,15,7,2.2,1.9,4.9,7.91,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,304,Mario Gomez,37,FW,NaN,5(4),498,3,1,1.4,0.3,0.2,6.72,0
306,306,Goran Pandev,39,M(CR),FW,17(12),1387,7,4,0.9,1.0,0.7,6.71,0
307,310,Victor Obinna,35,FW,NaN,4(6),398,2,0,1.8,0.7,0.9,6.71,0
308,316,Josip Ilicic,34,AM(CLR),FW,13(8),1108,3,1,1.9,1.0,0.9,6.71,0
309,318,Valter Birsa,36,M(CLR),FW,10(5),756,2,0,1.5,1.2,1.0,6.70,0

In [10]:
for i in range(len(df8)):
    if df8["WC_Rating"][i] == 0:
        df8.drop(i, inplace = True)

In [11]:
df8

Empty DataFrame
Columns: [Unnamed: 0, name, age, position1, position2, Apps, Mins, Goals, Assists, SpG, KeyP, Drb, Rating, WC_Rating]
Index: []

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#준비물  
#csv파일안에 독립변수(x)로 쓸 데이터 : goals, assists, etc
#csv파일안에 종속변수(y)로 쓸 데이터 : wc_rating -> 월드컵 csv파일에서 따로 가져와서 병합해야함
x=df8[['Goals', 'Assists', 'SpG', 'KeyP', 'Drb']]
y=df8['WC_Rating']

#과적합 막기 위해서 트레이닝, 테스트 데이터 분리
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.6, test_size=0.4)

#모델 생성 - 선형회귀 -> 결과안좋으면 로지스틱 회귀(소프트맥스) 함수 사용하는 것도 고려
model = LinearRegression()

#모델 훈련
model.fit(x_train, y_train)

#플롯으로 모델이 추측한 value & 테스트 value(정답) display
# plt.plot(model.predict(x_test, label=''))
# plt.plot(y_test.values.reshape(-1, 1), label='WC_Rating')
# plt.legend()

#오차 확인 -> 이거 결과 보고 가중치를 변경해야 겠지?
from sklearn.metrics import mean_absolute_error, mean_squared_error
#MAE 
mean_absolute_error(y_test, model.predict(x_test))
#MSE
MSE = mean_squared_error(y_test, model.predict(x_test))
#RMSE - 다른건 더 찾아보도록
RMSE = np.sqrt(MSE)

ValueError: With n_samples=0, test_size=0.4 and train_size=0.6, the resulting train set will be empty. Adjust any of the aforementioned parameters.

In [13]:
#x_test
#model.predict(x_test)
y_test.values

NameError: name 'y_test' is not defined

In [14]:
plt.plot(y_test.values.reshape(-1, 1), label='WC_Rating')

NameError: name 'y_test' is not defined

In [15]:
df10 = pd.read_csv("epl_predict.csv")
df10

,Unnamed: 0,name,age,position1,position2,Apps,Mins,Goals,Assists,SpG,KeyP,Drb,Fouled,Off,Disp,UnsTch,Rating
0,0,Kevin De Bruyne Man City,31,M(CLR),FW,25(5),2205,15,8,2.6,2.9,1.0,0.9,0.1,0.7,1.3,7.63
1,1,Mohamed Salah Liverpool,30,AM(CLR),FW,30(5),2763,23,13,4.0,1.8,1.5,0.7,0.3,2.3,2.8,7.54
2,2,Trent Alexander-Arnold Liverpool,23,D(R),M(R),32,2854,2,12,1.6,2.8,0.6,0.2,0.3,0.6,1.3,7.52
3,3,Son Heung-Min Tottenham,30,M(CLR),FW,35,3021,23,7,2.5,2.1,1.5,1,0.5,1.3,2.1,7.51
4,4,Kenedy Chelsea,26,D(L),M(LR),1,59,-,1,1.0,2.0,1.0,-,-,3.0,2.0,7.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,295,Mathias Normann Norwich,26,M(C),NaN,20(3),1653,1,2,1.1,0.6,0.7,1.2,-,0.7,1.2,6.56
296,296,Alex Oxlade Chamberlain Liverpool,29,M(CLR),NaN,9(8),787,2,1,1.2,0.6,0.7,0.2,0.1,0.6,0.9,6.55
297,297,Imrân Louza Watford,23,M(CLR),NaN,17(3),1423,-,-,0.9,0.8,0.7,0.7,-,0.5,1,6.55
298,298,Charlie Goode Brentford,27,D(C),NaN,4(2),448,-,-,0.3,1.2,0.8,1.2,-,0.2,0.5,6.55
299,299,Brandon Williams Norwich,21,D(L),M(L),23(3),2123,-,1,0.2,0.8,0.8,1.7,-,0.7,1.5,6.54

In [16]:
new_test = df10[['Goals', 'Assists', 'SpG', 'KeyP', 'Drb']]

In [17]:
new_test = new_test.replace("-", float(0))

In [18]:
model.predict(new_test)

NameError: name 'model' is not defined

In [ ]:
df10["pred_wc_rating"] = model.predict(new_test)

In [19]:
df10.to_csv("predict111.csv")

In [20]:
df_final = df10["pred_wc_rating"]
df_final.sort_values(ascending=False)
df10

KeyError: 'pred_wc_rating'

In [ ]:
x_list = ["Goals", "Drb", "Assists"]

In [ ]:
df10[x_list]

    Goals  Drb Assists
0      15  1.0       8
1      23  1.5      13
2       2  0.6      12
3      23  1.5       7
4       -  1.0       1
..    ...  ...     ...
295     1  0.7       2
296     2  0.7       1
297     -  0.7       -
298     -  0.8       -
299     -  0.8       1

[300 rows x 3 columns]

In [21]:
def linear_model(df_tr, df_pr, x_list):
    #df_tr = pd.read_csv(file_name_tr)
    x=df_tr[x_list]
    y=df_tr['WC_Rating']

    model = LinearRegression()

    model.fit(x, y)

    #df_pr = pd.read_csv(file_name_pr)
    x_pr=df_pr[x_list]
    y_pr=model.predict(x_pr)

    df_pr["WC_Rating"] = y_pr
    df_pr

In [22]:
df_tr = pd.read_csv("17_18_of_final.csv", encoding='cp949')
df_pr = pd.read_csv("21_22_of.csv", encoding='cp949')
x_list = ['Goals', 'Assists', 'SpG', 'KeyP', 'Drb']

In [23]:
linear_model(df_tr, df_pr, x_list)
df_pr

,Unnamed: 0,name,age,position1,position2,Apps,Mins,Goals,Assists,SpG,KeyP,Drb,Rating,WC_Rating
0,0,Robert Lewandowski,34,FW,NaN,34,2952,35,3,4.7,1.1,1.4,7.89,7.121331
1,1,Christopher Nkunku,24,M(CLR),FW,31(3),2735,20,13,2.4,1.9,1.9,7.64,7.036894
2,4,Erling Haaland,22,FW,NaN,21(3),1915,22,7,3.3,1.0,0.5,7.55,6.825482
3,5,Patrik Schick,26,AM(R),FW,26(1),2094,24,3,3.3,0.6,0.6,7.45,6.840871
4,6,Florian Wirtz,19,AM(C),NaN,22(2),1864,7,10,1.5,2.5,2.3,7.41,7.059510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,317,Riccardo Sottil,23,AM(LR),NaN,14(10),1245,3,2,0.9,0.6,1.1,6.47,6.722750
410,318,Federico Bonazzoli,25,AM(C),FW,19(13),1867,10,0,1.8,0.3,0.5,6.47,6.685869
411,322,Rey Manaj Spezia,25,FW,NaN,19(11),1768,5,0,1.8,0.4,0.7,6.47,6.705713
412,333,Federico Di Francesco,28,M(LR),FW,17(9),1378,5,0,1.0,0.5,0.5,6.45,6.638958
413,339,Dejan Kulusevski,22,AM(CR),FW,5(15),762,1,3,0.9,0.5,0.9,6.43,6.670548

In [24]:
df_pr = df_pr.sort_values("WC_Rating", ascending=False)

In [25]:
name_1 = df_pr.iloc[0].to_list()
name_2 = df_pr.iloc[1].to_list()

In [26]:
df_pr.iloc[0].to_list()[1]

'Kylian Mbapp? '

In [33]:
St = df_pr.iloc[0].to_list()[1]
Rw = df_pr.iloc[1].to_list()[1]
Lw = df_pr.iloc[2].to_list()[1]
Lm = df_pr.iloc[3].to_list()[1]
Cm = df_pr.iloc[4].to_list()[1]
Rm = df_pr.iloc[5].to_list()[1]
Lwb = df_pr.iloc[6].to_list()[1]
Lb = df_pr.iloc[7].to_list()[1]
Rb = df_pr.iloc[8].to_list()[1]
Rwb = df_pr.iloc[9].to_list()[1]
Gk = df_pr.iloc[10].to_list()[1]

In [35]:
st, rw, lw, lm, cm, rm, lwb, lb, rb, rwb, gk = linear_model(df_tr, df_pr, x_list, St, Rw, Lw, Lm, Cm, Rm, Lwb, Lb, Rb, Rwb, Gk)

'Robert Lewandowski '

In [ ]:
df22 = pd.read_csv("data/wc_2018/offensive.csv")
df22["country"]=""

In [ ]:
df22[df22["name"].str.contains(Country[0])]

,Unnamed: 0,name,age,position1,position2,Apps,Mins,Goals,Assists,SpG,KeyP,Drb,Fouled,Off,Disp,UnsTch,Rating,country
6,6,Lionel Messi Argentina,35,AM(CR),FW,4,360,1,2,4.5,2.5,5.8,4,-,4,2.3,7.87,Argentina
16,16,Lionel Messi Argentina,35,AM(CR),FW,4,360,1,2,4.5,2.5,5.8,4,-,4,2.3,7.87,Argentina
92,92,Éver Banega Argentina,34,M(C),NaN,2(1),216,-,2,1,1.3,2,1,-,1.7,2.3,7.11,Argentina
133,133,Nicolás Otamendi Argentina,34,D(C),NaN,4,360,-,-,1,-,-,1.3,-,0.3,0.5,6.98,Argentina
172,172,Eduardo Salvio Argentina,32,M(CR),NaN,2,146,-,-,0.5,1.5,1,2.5,-,-,1,6.90,Argentina
182,182,Gabriel Mercado Argentina,35,D(CR),NaN,3,270,1,1,0.3,0.3,0.3,1.7,-,-,0.7,6.86,Argentina
213,213,Marcos Rojo Argentina,32,D(CL),NaN,3,226,1,-,1,0.3,0.3,1.0,-,-,0.3,6.82,Argentina
259,259,Javier Mascherano Argentina,38,D(C),M(C),4,360,-,-,0.3,0.8,0.8,1.8,-,0.3,0.5,6.71,Argentina
261,261,Sergio Agüero Argentina,34,AM(CL),FW,2(2),178,2,-,1.5,0.3,0.8,0.3,0.5,0.3,2.3,6.71,Argentina
281,281,Ángel Di María Argentina,34,M(CLR),FW,3,237,1,-,1,0.7,1,2.3,1,2.3,1.3,6.66,Argentina
333,333,Maximiliano Meza Argentina,29,AM(CLR),NaN,2(2),208,-,-,0.8,1.8,1.3,1.8,0.3,0.5,2.3,6.56,Argentina
451,451,Nicolás Tagliafico Argentina,30,D(CL),NaN,4,350,-,-,0.8,1,0.5,1.8,-,-,0.5,6.31,Argentina
482,482,Lucas Biglia Argentina,36,DMC,NaN,1,54,-,-,2,-,-,1,-,1,1,6.23,Argentina
489,489,Marcos Acuña Argentina,30,D(L),M(CL),1,90,-,-,1,1,1,3,-,2,1,6.22,Argentina

In [ ]:
df22 = pd.read_csv("data/wc_2018/offensive.csv")
df22["country"]=""
for i in range(len(Country)):
    my_list = df22[df22["name"].str.contains(Country[i])]["Unnamed: 0"].to_list()
    df22.loc[my_list,"country"] = Country[i]
    my_list=[]

NameError: name 'pd' is not defined

In [ ]:
df22

NameError: name 'df22' is not defined

In [133]:
for i in range(len(df22["name"])):
    for k in range(len(Country)):
        df22[df22["name"].str.contains(Country[k])]["country"] = Country[k]
            
            df9["name"].str.replace(Country[i], "")

AttributeError: 'Series' object has no attribute 'contains'

In [1]:
St, Rw, Lw, Lm, Cm, Rm, Lwb, Lb, Rb, Rwb, Gk = []

ValueError: not enough values to unpack (expected 11, got 0)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df_tr = pd.read_csv("./data/17_18_of_new.csv")
df_pr = pd.read_csv("./data/21_22_of_new.csv")
x_list = ['Goals', 'Assists', 'SpG', 'KeyP', 'Drb']

In [2]:
St = "st" 
Rw = "rw" 
Lw = "lw" 
Lm = "lm" 
Cm = "cm" 
Rm = "rm" 
Lwb = "lwb" 
Lb = "lb" 
Rb = "rb" 
Rwb = "rwb" 
Gk ="gk"

In [5]:
x=df_tr[x_list]
y=df_tr['WC_Rating']

model = LinearRegression()

model.fit(x, y)

#df_pr = pd.read_csv(file_name_pr)
x_pr=df_pr[x_list]
y_pr=model.predict(x_pr)

df_pr["WC_Rating"] = y_pr

df_pr = df_pr.sort_values("WC_Rating", ascending=False)
        
St = df_pr.iloc[0].to_list()[1]
Rw = df_pr.iloc[1].to_list()[1]
Lw = df_pr.iloc[2].to_list()[1]
# Lm = df_pr.iloc[3].to_list()[1]
# Cm = df_pr.iloc[4].to_list()[1]
# Rm = df_pr.iloc[5].to_list()[1]
# Lwb = df_pr.iloc[6].to_list()[1]
# Lb = df_pr.iloc[7].to_list()[1]
# Rb = df_pr.iloc[8].to_list()[1]
# Rwb = df_pr.iloc[9].to_list()[1]
# Gk = df_pr.iloc[10].to_list()[1]

In [6]:
St, Rw, Lw

('Kylian Mbappé ', 'Allan Saint-Maximin ', 'Adama Traoré ')

In [1]:
x_list = {'Goals': True, 'Assists': False, 'SpG': True, 'KeyP': True, 'Drb': False}

In [7]:
x_list["Goals"]

True

In [8]:
x_list1 = []
if(x_list["Goals"] == True):
    x_list1.append("Goals")

In [9]:
x_list1

['Goals']

In [10]:
x_list1 = []
if(x_list["Goals"] == True):
    x_list1.append("Goals")
if(x_list["Assists"] == True):
    x_list1.append("Assists")
if(x_list["SpG"] == True):
    x_list1.append("SpG")
if(x_list["KeyP"] == True):
    x_list1.append("KeyP")
if(x_list["Drb"] == True):
    x_list1.append("Drb")

In [11]:
x_list1

['Goals', 'SpG', 'KeyP']